export const CONFIG_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  ACCESS_JWT_SECRET: 'ACCESS_JWT_SECRET',
  ACCESS_JWT_EXPIRES_IN: 'ACCESS_JWT_EXPIRES_IN',
  REFRESH_JWT_SECRET: 'REFRESH_JWT_SECRET',
  REFRESH_JWT_EXPIRES_IN: 'REFRESH_JWT_EXPIRES_IN',
  BCRYPT_PEPPER: 'BCRYPT_PEPPER',
  BCRYPT_SALT_ROUNDS: 'BCRYPT_SALT_ROUNDS',
  MONGO_URI: 'MONGO_URI',
};

export const APP_CONSTANTS = {
  PRODUCTION: 'production',
  DEV: 'dev',
  UNKNOWN_SESSION: 'unknown-session',
  REFRESH_TOKEN_KEY: 'refreshToken',
  LOCAL_APP_FRONTEND_URL: 'http://localhost:5173',
};

export const COOKIES_CONSTANTS = {
  ONE_MONTH: 30 * 24 * 60 * 60 * 1000,
};

export const JWT_CONSTANTS = {
  FIVE_MINUTES: '5m',
  ONE_MONTH: '30d'
};

export const SESSION_CONSTANTS = {
  SESSION_ID_HEADER: 'x-session-id',
};
